version: '3.4'

services:
  frontend:
    image: gnc-front-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    ports:
      - '${FRONT_PORT:-4000}:4000'

  backend:
    image: gnc-back-dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - ./VERSION:/VERSION
      - ./config:/config
      - ./external_modules:/external_modules
      - ./media:/media
    ports:
      - '${API_PORT:-5002}:5002'

  db:
    ports:
      - '${DB_PORT:-8465}:5432'

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '${NGINX_PORT:-80}:80'
