name: "‚úÖ Linter"

on:
  push:
    branches: [master, dev]
    paths:
      - "backend/**/*.py"
      - "frontend/*"

  pull_request:
    branches: [master, dev]
    paths:
      - "backend/**/*.py"
      - "frontend/*"

env:
  BACKEND_FOLDER: "backend"
  FRONTEND_FOLDER: "frontend"
  PYTHON_VERSION: 3.9

jobs:
  lint-py:
    name: Python üêç

    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install project requirements
        run: |
          poetry install

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 ${{ env.BACKEND_FOLDER }} --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 ${{ env.BACKEND_FOLDER }} --count --exit-zero --statistics

  lint-node:
    name: NodeJS üêç
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: "${{ env.BACKEND_FOLDER }}/.nvmrc"
      - run: cd ${{ env.BACKEND_FOLDER }} && npm ci
      - run: cd ${{ env.BACKEND_FOLDER }} && npm run lint
