# This is a basic workflow that is manually triggered

name: Test install
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [master, dev]
    paths:
      - "backend/**"
      - "frontend/**"
      - "install/**"
      - ".github/workflows/test_install.yml"

  pull_request:
    branches: [master, dev]
    paths:
      - "backend/**"
      - "frontend/**"
      - "install/**"
      - ".github/workflows/test_install.yml"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        node-version: ["14.21.3"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: Init NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Init python ${{ matrix.node-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: enable postgresql
        run: sudo systemctl start postgresql.service
      - name: Test install
        run: cp config/settings.ini.template config/settings.ini && sed -i 's,http://mydomain.net/taxhub/api/,https://demo.geonature.fr/taxhub/api/,g' config/settings.ini && install/install_app.sh
